# Generated by Django 4.2.2 on 2023-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='author',
            field=models.CharField(default='aaa', max_length=100),
        ),
    ]
